### ISSUE TITLE
How To Pass a Parameter in URL

### ISSUE THREAD

**Issue by zmoddynamics** [thelfensdrfer/yii2sshconsole#2]
Hi, 
I'm using your controller to invoke a shell command like this:

`use \yii2sshconsole\Controller;
class SshController extends Controller
{
 public function actionExample($q=null)
 {
 echo $q;
 }
}`
Then, calling the url : example.com/ssh/example/1
gives the following error:
Unknown option: --q

I've also tried calling the url: example.com/ssh/example?q=1
gives the following error:
Unknown option: --q

Can I not pass a parameter in the URL because your class extends console/Controller and not yii\base\Controller ? 

Is there a solution ?

**Comment by zmoddynamics** [comment]
Hi, well I just realized your controller does not extend from Yii\web\Controller  so it doesn't accept parameters from URL. I solved this by doing the following in normal Yii web controller, but would be interested in your thoughts?
`use Yii;`
`use yii\web\Controller;`
`class websshController extends Controller {`
`public function actionExample($q=null)`
`{`
        `$myssh = (new \yii2sshconsole\Controller('id',null,[]));`
        `//do your magic $myssh->connect([]); $myssh->run([]); etc..`

`}`
`}`

url: example.com/webssh/example/?q=1 .. this works.. thanks

**Comment by thelfensdrfer** [comment]
Hi, your workaround seems fine. I only created this extension to help me with deployments etc. and think it's a security risk to execute ssh commands via url parameters. But if you feel comfortable with it, I'm fine too;) Thanks for sharing your solution.
