### ISSUE TITLE
Issue on connecting credentials

### ISSUE THREAD

**Issue by mundoEarth** [thelfensdrfer/yii2sshconsole#3]
Hello,

I'm having an issue on ss, it cannot connect via ssh using php code but when I'm using mysql workbench using ssh credentials I can logge in and connect successfully. How can I put the same credentials from mysql workbench in the php code?

**Comment by thelfensdrfer** [comment]
Hi,

if you have a username and password you can connect via

```php
$this->connect('example.com', [
	'username' => 'myusername',
	'password' => 'mypassword', // optional
]);
```

If you have a ssh key you can connect via

```php
$this->connect('example.com', [
	'username' => 'myusername',
	'key' => '/path/to/private.key',
	'password' => 'mykeypassword', // optional
]);
```

**Comment by mundoEarth** [comment]
Hi @thelfensdrfer ,  I used the above code but it did not work on me. Is it possible the firewall rule of the server where my db stored?

**Comment by thelfensdrfer** [comment]
Well, if you can connect with the mysql workbench over ssh, ssh works and is not blocked. I don't know what the reason might be, the only thing I know is, it worked before on some other systems ;)
