### ISSUE TITLE
Public and private RSA key

### ISSUE THREAD

**Issue by vakaman** [thelfensdrfer/yii2sshconsole#5]
I'm trying to use the public and private key, generated by Putty, but when i use the two keys on putty, it works fine, but if i try to use the key's on your code, i get the following error: INVALID SIZE
What is the way that you did, to generate the private and public key, to use with your code?

thank you so much

**Comment by thelfensdrfer** [comment]
I am using linux or mac. The Keys which are generated with putty are different. Here are detailed instructions on how to use/convert the keys: https://stackoverflow.com/a/2224204/1100089
